name: Deploy Global Infrastructure

# This workflow only runs when manually triggered
on:
  workflow_dispatch:

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  LOCATION: "North Europe"

jobs:
  deploy-global:
    name: Deploy Global Infrastructure
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      # Step 3: Initialize Terraform for the global folder
      - name: Terraform Init for Global
        run: terraform -chdir=global init

      # Step 4: Terraform Plan for Global
      - name: Terraform Plan for Global
        run: terraform -chdir=global plan -var="subscription_id=${{ env.ARM_SUBSCRIPTION_ID }}" -var="tenant_id=${{ env.ARM_TENANT_ID }}" -var="client_id=${{ env.ARM_CLIENT_ID }}" -var="client_secret=${{ env.ARM_CLIENT_SECRET }}" -var="location=${{ env.LOCATION }}" -out=tfplan-global

      # Step 5: Terraform Apply for Global
      - name: Terraform Apply for Global
        run: terraform -chdir=global apply -auto-approve tfplan-global
