name: Terraform CI/CD

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - dev
      - staging
      - prod
  workflow_dispatch: # Allows manual triggering from the GitHub Actions interface

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
  STORAGE_ACCOUNT_CONTAINER: ${{ secrets.STORAGE_ACCOUNT_CONTAINER || 'tfstate' }}
  PROJECT_NAME: ${{ secrets.PROJECT_NAME || 'akseles-operaterra' }}
  GLOBAL_RESOURCE_GROUP: ${{ secrets.GLOBAL_RESOURCE_GROUP ||'akseles-operaterra-global' }}
  # Those three last ones can be saved to secrets, but are here prefilled (non-secret information) based on what should have been created running /global/main.tf

jobs:
  validate:
    name: Terraform Validate and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install TFSec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: TFLint
        run: tflint

      - name: Tfsec (Security Check)
        run: tfsec ./deployments

  deploy:
    name: Terraform Environment Deployments
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform -chdir=deployments init -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ env.STORAGE_ACCOUNT_CONTAINER }}" -backend-config="key=${{ github.ref_name }}.terraform.tfstate" -backend-config="subscription_id=${{ env.ARM_SUBSCRIPTION_ID }}" -backend-config="resource_group_name=${{ env.GLOBAL_RESOURCE_GROUP }}"

      - name: Terraform Plan
        run: terraform -chdir=deployments plan -var="subscription_id=${{ env.ARM_SUBSCRIPTION_ID }}" -var="tenant_id=${{ env.ARM_TENANT_ID }}" -var="client_id=${{ env.ARM_CLIENT_ID }}" -var="client_secret=${{ env.ARM_CLIENT_SECRET }}" -var="state_storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" -var="state_container_name=${{ env.STORAGE_ACCOUNT_CONTAINER }}" -var="environment=${{ github.ref_name }}" -var="project_name=${{ env.PROJECT_NAME }}" -var="state_resource_group_name=${{ env.GLOBAL_RESOURCE_GROUP }}" -out=tfplan-${{ github.ref_name }}

      - name: Terraform Apply
        run: terraform -chdir=deployments apply -auto-approve tfplan-${{ github.ref_name }}

      # - name: Terraform Init for Deployments
      #   run: terraform -chdir=deployments init -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" -backend-config="container_name=${{ env.STORAGE_ACCOUNT_CONTAINER }}" -backend-config="key=${{ github.ref_name }}.terraform.tfstate" -backend-config="subscription_id=${{ env.ARM_SUBSCRIPTION_ID }}" -backend-config="resource_group_name=${{ env.GLOBAL_RESOURCE_GROUP }}"

      # - name: Terraform Plan for Deployments
      #   run: terraform -chdir=deployments plan -var="state_storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" -var="state_container_name=${{ env.STORAGE_ACCOUNT_CONTAINER }}" -var="state_resource_group=${{ env.GLOBAL_RESOURCE_GROUP }}" -var="environment=${{ github.ref_name }}" -out=tfplan-deployments

      # - name: Terraform Apply for Deployments
      #   run: terraform -chdir=deployments apply -auto-approve tfplan-deployments
